---DATA ABOUT ALL MENUS---
CREATE TABLE MENU (
    MENU_ID INT IDENTITY PRIMARY KEY, 
    MENU_NAME VARCHAR(50), 
    MENU_INFO VARCHAR(100)
    );
---DATA ABOUT ALL RECIPES---
CREATE TABLE RECIPE (
    RECIPE_ID INT IDENTITY PRIMARY KEY, 
    RECIPE_NAME VARCHAR(50), 
    RECIPE_INFO VARCHAR(100)
    );
---DATA ABOUT ALL INGREDIENTS---
CREATE TABLE INGREDIENT (
    INGREDIENT_ID INT IDENTITY PRIMARY KEY, 
    INGREDIENT_NAME VARCHAR(50),
    INGREDIENT_INFO VARCHAR(100)
    );
---DATA ABOUT ALL INSTRUCTIONS---
CREATE TABLE INSTRUCTION (
    INSTRUCTION_ID INT IDENTITY PRIMARY KEY, 
    INSTRUCTION_NAME VARCHAR(50), 
    INSTRUCTION_INFO VARCHAR(100)
    );
---CONNECTION BETWEEN MENU AND RECIPE---
CREATE TABLE MENU_INCLUDE(
    MENU_ID INT REFERENCES MENU(MENU_ID), 
    RECIPE_ID INT REFERENCES RECIPE(RECIPE_ID), 
    CONSTRAINT PK_MENU_INCLUDE PRIMARY KEY (MENU_ID, RECIPE_ID)
	);
---CONNECTION BETWEEN RECIPE AND INSTRUCTIONM---
CREATE TABLE RECIPE_STEP(
    RECIPE_ID INT REFERENCES RECIPE(RECIPE_ID), 
	STEP_NUM INT IDENTITY,
    INSTRUCTION_ID INT REFERENCES INSTRUCTION(INSTRUCTION_ID), 
    CONSTRAINT PK_RECIPE_STEP PRIMARY KEY (RECIPE_ID, STEP_NUM)
    );
---CONNECTION BETWEEN INSTRUCTION AND INGREDIENT---
CREATE TABLE RECIPE_STEP_INGREDIENT(
    RECIPE_ID INT NOT NULL,
    STEP_NUM INT NOT NULL,
    INGREDIENT_ID INT REFERENCES INGREDIENT(INGREDIENT_ID),
    ---NUMBER OF THE INGREDIENT---
	AMOUNT INT, 
    CONSTRAINT FK_RECIPE_STEP_ID FOREIGN KEY (RECIPE_ID, STEP_NUM) REFERENCES RECIPE_STEP(RECIPE_ID, STEP_NUM),
    CONSTRAINT PK_RECIPE_STEP_INGREDIENT PRIMARY KEY(RECIPE_ID, STEP_NUM, INGREDIENT_ID)
    );
